version: '3.9'
services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:latest
#    todo env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:${DB_PORT}:${DB_PORT}